# Generated by Django 2.0.6 on 2018-06-11 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180611_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmember',
            old_name='member',
            new_name='member_id',
        ),
    ]
