# Generated by Django 2.0.6 on 2018-06-14 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projectlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectlist',
            name='owner',
        ),
        migrations.DeleteModel(
            name='ProjectList',
        ),
    ]
