# Generated by Django 2.0.6 on 2018-06-13 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_project_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmember',
            options={'ordering': ('project', 'member')},
        ),
    ]
